id: "m2-8queens-objective"
type: "short-answer"
chapter: 1
question: |
  **Implement the famous sugar scape multi-agent system**

  **Level 0**  Discuss the philosophical significance of agents and environments.  What is "intelligence"?  What is "artificial intelligence"?
  
  **Level 1**  Describe the famous sugar scape multi-agent system.  What are the agents, the environment, and the rules?  How do the agents interact with each other and the environment?  What kinds of "emergent behaviors" arise?

  **Level 2**  Implement sugar scape in a language of your choice.  Simulate the system and observe the emergent behaviors.  How do different parameters (e.g., initial distribution of sugar, agent metabolism, vision range) affect the outcomes?

  **Level 3**  In what ways could the agents be improved to make them more intelligent (from simple reflex, to: model-based, goal-based, utility-based)?  How might the key topics of this course (search, optimization, constraint satisfaction, adversarial reasoning, logical inference, probabilistic reasoning, and learning) serve to raise the "intelligence level" of these agents?  How intelligent do agents have to be for the system to be interesting?
answer: |
topics:
  - "Agents"
  - "Environments"
example_videos:
  - "https://www.youtube.com/watch?v=xouin83ebxE"
